# ==========================================
# Export PDF Report
# ==========================================

from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer
from reportlab.lib.styles import getSampleStyleSheet

from tkinter import filedialog, messagebox

from datetime import datetime

from utils.helper import (
    get_total_income,
    get_total_expense,
    get_balance,
    get_budget,
    get_recent_transactions
)


def export_to_pdf(user):

    filename = filedialog.asksaveasfilename(
        defaultextension=".pdf",
        filetypes=[
            ("PDF File", "*.pdf")
        ],
        initialfile="Expense_Report.pdf"
    )

    if filename == "":
        return

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b><font size=20>Expense Tracker Report</font></b>", styles["Title"])
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Generated :</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            f"<b>Total Income :</b> ₹ {get_total_income(user[0]):,.2f}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Total Expense :</b> ₹ {get_total_expense(user[0]):,.2f}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Balance :</b> ₹ {get_balance(user[0]):,.2f}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Monthly Budget :</b> ₹ {get_budget(user[0]):,.2f}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Recent Transactions</b>", styles["Heading2"])
    )

    story.append(Spacer(1, 10))

    transactions = get_recent_transactions(user[0])

    if transactions:

        for row in transactions:

            story.append(
                Paragraph(
                    f"{row[0]} | {row[3]} | {row[1]} | ₹ {row[2]}",
                    styles["Normal"]
                )
            )

    else:

        story.append(
            Paragraph("No Transactions Found", styles["Normal"])
        )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by Expense Tracker</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)

    messagebox.showinfo(
        "Success",
        "PDF Report Generated Successfully!"
    )